// Generated by CoffeeScript 1.8.0
(function() {
  var jade_data;

  jade_data = {
    title: 'The Site Title',
    env: 'dev',
    description: 'This is the SEO description'
  };

  module.exports = function(grunt) {
    var target;
    target = grunt.option('target') || 'dev';
    grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      uglify: {
        production: {
          files: {
            'dest/js/bundle.js': ['bower_components/jquery/dist/jquery.js', 'bower_components/jquery-cycle2/build/jquery.cycle2.js']
          }
        }
      },
      cssmin: {
        production: {
          files: {
            'dest/css/bundle.css': ['bower_components/bootstrap/dist/css/bootstrap.css', 'out/css/futura.css', 'out/css/style.css']
          }
        }
      },
      copy: {
        css: {
          expand: true,
          flatten: true,
          src: 'src/css/*.css',
          dest: 'out/css/'
        },
        production: {
          expand: true,
          flatten: true,
          src: 'out/*.html',
          dest: 'dest/'
        }
      },
      stylus: {
        options: {
          compress: false
        },
        compile: {
          files: {
            'out/css/style.css': 'src/css/*.styl'
          }
        }
      },
      jade: {
        compile: {
          options: {
            data: jade_data,
            pretty: true
          },
          files: {
            'out/index.html': ['src/*.jade']
          }
        },
        production: {
          options: {
            data: function() {
              jade_data.env = 'production';
              return jade_data;
            },
            pretty: false
          },
          files: {
            'out/index.html': ['src/*.jade']
          }
        }
      },
      watch: {
        css: {
          files: ['src/css/*.css'],
          tasks: ['copy'],
          options: {
            livereload: true
          }
        },
        styl: {
          files: ['src/css/*.styl'],
          tasks: ['stylus'],
          options: {
            livereload: true
          }
        },
        jade: {
          files: ['src/index.jade', 'src/jade/*.jade'],
          tasks: ['jade'],
          options: {
            livereload: true
          }
        }
      },
      clean: ['out', 'dest']
    });
    grunt.loadNpmTasks('grunt-contrib-stylus');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-jade');
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-copy');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.registerTask('default', ['build', 'watch']);
    grunt.registerTask('build', ['clean', 'stylus', 'jade', 'copy:css']);
    return grunt.registerTask('export', ['build', 'copy:production', 'cssmin:production', 'uglify:production']);
  };

}).call(this);
